#!/usr/bin/env bash
# Installs, configures, and starts server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "GSM Arena" | sudo tee /var/www/html/index.nginx-debian.html

# configure redirection
new_str="\\\trewrite ^/redirect_me https://www.gsmarena.com\
wu4 permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default
sudo service nginx restart
