#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "GSM Arena" > /var/www/html/index.nginx-debian.html

# configure redirection
new_str="\\\trewrite ^/redirect_me https://www.gsmarena.com\
wu4 permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default

# create custom error 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error404
# configure custom error page to be served
new_str="\\\terror_page 404 /error404;"
sudo sed -i "43i $new_str" /etc/nginx/sites-available/default

# restart nginx server
sudo service nginx restart
