#!/usr/bin/env bash
# Install Haproxy and configures two servers for  load balancing

sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\*
sudo apt update && sudo apt upgrade -y

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

sudo sed -i "$ a\listen 77413-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?stats\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 77413-web-01 107.23.21.154:80 check\n\tserver 77413-web-02 100.25.148.14:80 check\n\t" /etc/haproxy/haproxy.cfg

sudo service haproxy start
~
