#!/usr/bin/env bash
# creates file /var/run/myscript.pid cointaining PID,
# display To infinity and beyond indefinitely,
# display I hate the kill command when receiving a SIGTERM signal,
# display Y U no love me?! when receiving a SIGINT signal
# delete file /var/run/myscript.pid and terminates itself 
# when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$' > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid;
	exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit'
SIGQUIT
done
