#!/usr/bin/env bash
#displays 1 to 100 replacing multiple of 3 and 5 by Fizz and Buzz repectively; 
#both by FizzBuzz

count=1
while [ $count -lt 101 ]
do
	if [ $((count%15)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((count%3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((count%5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count+=1))
done 
