#!/usr/bin/env bash
# displays content of /etc/passwd
input="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1 is part of the $f4 gang,\n
	lives in $f6 and rides $f7. $f3's place\n
	is protected by the passcode $f2, more\n
	info about the user here: $f5\n"
done < "$input"
