#!/usr/bin/env bash
# displays "Best School" 8 times "Hi" and "Best School"

count=0
while [ $count -lt 11 ]
do
	if [ $count == 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	let count+=1
done
