#!/usr/bin/env bash
# displays numbers 1 to 20 with texts at specific positions

Count=1
while (($count < 21))
do
	case $count in
		4)
			echo $count
			echo "bad luck from China"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17)
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	((count+=1))
done
