#!/usr/bin/env bash
# Program prints from 0 hours to 12 hrs 59 mins

hrs=0
while [ $hrs -lt 13 ]
do
	echo Hour: $hrs
	mins=1
	while [ $mins -lt 60 ]
	do
		echo $mins
		((mins+=1))
	done
	((hrs+=1))
done
