#!/usr/bin/env bash
# write a script that configures server with the information
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
# sed ... ~/hosts.new
sed -i s/^127.*$/"127.0.0.2	localhost"/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
#cp -f ~/hosts.new /etc/hosts
cat ~/hosts.new > /etc/hosts
